apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-python
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-python
  template:
    metadata:
      labels:
        app: hello-world-python
    spec:
      containers:
        - name: hello-world-python
          image: geetha8500/hello-world-python:latest  # Will be updated by Jenkins
          ports:
            - containerPort: 5000
